### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by kleinzcy** [bobwan1995/PMFNet#1]
Thanks to your work!

I notice this article in the resume of professor xuming he. But I can't find files. Beacause I will attend the interview of SIST next day. I want to read some papers of professor xuming he to understand his research. And I have some other questions. My qq is 1014941627, and my mail is zcy_ai@whu.edu.cn.

I would be very appreciate if you can help me. Thanks!

**Comment by bobwan1995** [comment]
Thank you for your interest in our paper. I'm sorry that I didn't reply it in time because I was on vacation in the last week. I've just committed it to Arxiv and it will be available in 2-3 days.
My email address is _wanbo at shanghaitech.edu.cn_ . If you are interested in our group, please contact me in that way.

**Comment by bobwan1995** [comment]
Available at _https://arxiv.org/pdf/1909.08453.pdf_
